version: '2'
services:
  redis:
    image: redis:3.2.5-alpine

  couchdb:
    image: couchdb:1.6.1

  web:
    depends_on:
      - couchdb
      - redis

    environment:
      - COUCHDB_PORT=tcp://couchdb:5984
      - REDIS_PORT=tcp://redis:6379

    image: my-nodejs-app4:latest
    ports:
      - "8050:8050"
